language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libeigen3-dev libyaml-cpp-dev libboost-dev cmake

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
